# Generated by Django 3.2.9 on 2021-12-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('Project_id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=50)),
                ('Project_details', models.CharField(max_length=500)),
                ('Total_target', models.IntegerField()),
                ('Total_donations', models.IntegerField()),
                ('Avg_rate', models.FloatField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projectreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_project', models.CharField(max_length=1000)),
                ('preport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
                ('reportprojectuser_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projectpictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('Iproject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Projectcomments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('cproject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
                ('cuser_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentsreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_comment', models.CharField(max_length=1000)),
                ('creport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectcomments')),
                ('reportcommentuser_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
