# Generated by Django 3.2.9 on 2021-12-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
